name: Generate GitHub Contribution Snake

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  generate-snake:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境执行工作流

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 检出代码仓库

      - name: Generate Snake Graph
        uses: Platane/snk@v3.2.0  # 使用 Platane/snk Action 生成蛇形图
        with:
          github_user_name: ${{ github.repository_owner }}  # 使用仓库拥有者的 GitHub 用户名
          
          # 生成蛇形图的输出文件路径
          outputs: |
            dist/github-snake.svg  # 默认输出文件路径
            dist/github-snake-dark.svg?palette=github-dark  # 暗黑模式的蛇形图
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9  # 另一种颜色方案的蛇形图
          
      - name: Commit and Push Snake Graph
        run: |
          git config --global user.name "Dynamite2003"
          git config --global user.email "shizy22@mails.tsinghua.edu.cn"
          git add dist/*.svg dist/*.gif
          git commit -m "Add GitHub Contribution Snake"
          git push origin main  # 将生成的蛇形图推送回 GitHub 仓库
